In [1]:
import requests

url = "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Industry_and_Mining/MapServer/0/query"

params = {
    "where": "1=1",
    "outFields": "*",
    "f": "geojson",
    "resultRecordCount": 5
}

response = requests.get(url, params=params)
print("Status code:", response.status_code)
data = response.json()
print("Number of features:", len(data.get("features", [])))

Status code: 200
Number of features: 5

In [2]:
import json

# Look at the structure of one feature in detail
print(json.dumps(data["features"][0], indent=2))

{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      122.48074457062543,
      -28.56509153525137
    ]
  },
  "properties": {
    "oid": 1,
    "gid": 11226143,
    "site_code": "S0000001",
    "site_title": "Pieces of Eight - Admiral Hill",
    "short_name": "Pieces of Eight",
    "site_commo": "Au, Ag",
    "site_type_": "Mine",
    "site_sub_t": "Openpit",
    "site_stage": "Care and Maintenance",
    "target_com": "GOLD",
    "commodity": "PRECIOUS METAL",
    "proj_code": "J00238",
    "proj_title": "Laverton - Barnicoat - Karridale - Merolia / Focus",
    "confidenti": "Public",
    "point_conf": "Public",
    "latitude": -28.565078,
    "longitude": 122.480754,
    "web_link": "https://minedex.dmirs.wa.gov.au/Web/common/jump.jsp?jumpType=SITE&id=S0000001",
    "extract_da": 1788307200000
  }
}

In [3]:

count_params = {
    "where": "1=1",
    "returnCountOnly": "true",
    "f": "json"
}

count_response = requests.get(url, params=count_params)
count_data = count_response.json()
print("Total records:", count_data.get("count"))

Total records: 48414

In [4]:
# Check the service's maximum records per request
info_url = "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Industry_and_Mining/MapServer/0"
info_params = {"f": "json"}

info_response = requests.get(info_url, params=info_params)
info_data = info_response.json()
print("Max record count per request:", info_data.get("maxRecordCount"))

Max record count per request: 10000

In [5]:
all_features = []
offset = 0
page_size = 10000

while True:
    page_params = {
        "where": "1=1",
        "outFields": "*",
        "f": "geojson",
        "resultRecordCount": page_size,
        "resultOffset": offset
    }
    page_response = requests.get(url, params=page_params)
    page_data = page_response.json()
    features = page_data.get("features", [])

    if not features:
        break

    all_features.extend(features)
    print(f"Fetched {len(features)} records, total so far: {len(all_features)}")
    offset += page_size

print(f"\nFinished. Total records fetched: {len(all_features)}")

Fetched 10000 records, total so far: 10000
Fetched 10000 records, total so far: 20000
Fetched 10000 records, total so far: 30000
Fetched 10000 records, total so far: 40000
Fetched 8414 records, total so far: 48414

Finished. Total records fetched: 48414

In [6]:
import pandas as pd

# Extract properties and coordinates into a flat structure
records = []
for feature in all_features:
    props = feature["properties"].copy()
    geom = feature.get("geometry")
    if geom and geom.get("type") == "Point":
        props["longitude"] = geom["coordinates"][0]
        props["latitude"] = geom["coordinates"][1]
    else:
        props["longitude"] = None
        props["latitude"] = None
    records.append(props)

df = pd.DataFrame(records)
df.shape

(48414, 19)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48414 entries, 0 to 48413
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   oid         48414 non-null  int64
 1   gid         48414 non-null  int64
 2   site_code   48414 non-null  str
 3   site_title  48414 non-null  str
 4   short_name  48414 non-null  str
 5   site_commo  48414 non-null  str
 6   site_type_  48414 non-null  str
 7   site_sub_t  48414 non-null  str
 8   site_stage  48414 non-null  str
 9   target_com  48414 non-null  str
 10  commodity   48414 non-null  str
 11  proj_code   48414 non-null  str
 12  proj_title  48414 non-null  str
 13  confidenti  48414 non-null  str
 14  point_conf  48414 non-null  str
 15  latitude    48414 non-null  float64
 16  longitude   48414 non-null  float64
 17  web_link    48414 non-null  str
 18  extract_da  48414 non-null  int64
dtypes: float64(2), int64(3), str(14)
memory usage: 7.0 MB

In [8]:
# Check for empty strings or placeholder values in text columns
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    empty_count = (df[col].str.strip() == '').sum()
    if empty_count > 0:
        print(f"{col}: {empty_count} empty strings")

C:\Users\pjvas\AppData\Local\Temp\ipykernel_4828\3620000863.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include='object').columns

site_commo: 4 empty strings
target_com: 8 empty strings
commodity: 2 empty strings
proj_code: 5773 empty strings
proj_title: 5773 empty strings

In [9]:
# Western Australia's approximate bounding box
# Latitude: -35 to -14, Longitude: 112 to 129

invalid_coords = df[
    (df['latitude'] > -14) | (df['latitude'] < -35) |
    (df['longitude'] < 112) | (df['longitude'] > 129)
]

print(f"Records with coordinates outside WA bounds: {len(invalid_coords)}")
invalid_coords[['site_title', 'latitude', 'longitude']].head(10)

Records with coordinates outside WA bounds: 128

,site_title,latitude,longitude
1347,Cape Bougainville Group,-13.960054,126.097099
2178,Port Harding - Torbay,-35.070160,117.644501
4203,Cape Bougainville North,-13.960054,126.097099
4289,Denmark - Ocean Beach,-35.031766,117.326854
4544,Christmas Island Phosphate,-10.498459,105.651588
16718,Bornholm / Wolfe SH (70),-35.058134,117.573284
16758,Gledhow South (70),-35.042751,117.791636
16843,Parry Beach (70),-35.044348,117.140718
17234,Gumboot Bay Barge Facility,-13.967330,127.207497
17256,Christmas Island Limestone - Phosphate Hill Qu...,-10.421943,105.694800

In [10]:
df['site_type_'].value_counts()

site_type_
Mine                      23889
Prospect                   6701
Infrastructure             6084
Occurrence                 4806
Deposit                    3626
Other                      1849
Target                     1452
Geological Observation        6
Unknown                       1
Name: count, dtype: int64

In [11]:
df['site_stage'].value_counts()

site_stage
Shut                    20248
Undeveloped             16689
Proposed                 4568
Operating                4561
Care and Maintenance     2113
Under Development         235
Name: count, dtype: int64

In [12]:
def classify_location(lat, lon):
    if -35.5 <= lat <= -13.5 and 112 <= lon <= 129.5:
        return "WA Mainland"
    elif -10.7 <= lat <= -10.3 and 105.5 <= lon <= 105.8:
        return "Christmas Island"
    elif -12.3 <= lat <= -12.0 and 96.7 <= lon <= 97.0:
        return "Cocos (Keeling) Islands"
    else:
        return "To be confirmed"

df['location_region'] = df.apply(lambda row: classify_location(row['latitude'], row['longitude']), axis=1)

df['location_region'].value_counts()

location_region
WA Mainland         48407
Christmas Island        4
To be confirmed         3
Name: count, dtype: int64

In [13]:
df[df['location_region'] == 'To be confirmed'][['site_title', 'latitude', 'longitude', 'site_type_', 'commodity']]

       site_title   latitude   longitude site_type_         commodity
37867   Feature P -11.323986  126.726009     Target  PRECIOUS MINERAL
37986      Fohn 1 -11.008086  127.140459     Target  PRECIOUS MINERAL
37987  Fohn South -11.080946  127.154549     Target  PRECIOUS MINERAL

In [14]:
def classify_location(lat, lon):
    if -35.5 <= lat <= -13.0 and 112 <= lon <= 129.5:
        return "WA Mainland"
    elif -10.7 <= lat <= -10.3 and 105.5 <= lon <= 105.8:
        return "Christmas Island"
    elif -12.3 <= lat <= -12.0 and 96.7 <= lon <= 97.0:
        return "Cocos (Keeling) Islands"
    else:
        return "To be confirmed"

df['location_region'] = df.apply(lambda row: classify_location(row['latitude'], row['longitude']), axis=1)

df['location_region'].value_counts()

location_region
WA Mainland         48407
Christmas Island        4
To be confirmed         3
Name: count, dtype: int64

In [15]:
def classify_location(lat, lon):
    if -35.5 <= lat <= -10.5 and 112 <= lon <= 129.5:
        return "WA Mainland"
    elif -10.7 <= lat <= -10.3 and 105.5 <= lon <= 105.8:
        return "Christmas Island"
    elif -12.3 <= lat <= -12.0 and 96.7 <= lon <= 97.0:
        return "Cocos (Keeling) Islands"
    else:
        return "To be confirmed"

df['location_region'] = df.apply(lambda row: classify_location(row['latitude'], row['longitude']), axis=1)

df['location_region'].value_counts()

location_region
WA Mainland         48410
Christmas Island        4
Name: count, dtype: int64

In [16]:
df.to_csv('data/mining_sites_clean.csv', index=False)
print(f"Saved {len(df)} rows and {len(df.columns)} columns to mining_sites_clean.csv")

OSError: Cannot save file into a non-existent directory: 'data'

In [17]:
df.to_csv('data/mining_sites_clean.csv', index=False)
print(f"Saved {len(df)} rows and {len(df.columns)} columns to mining_sites_clean.csv")

Saved 48414 rows and 20 columns to mining_sites_clean.csv

In [18]:
import pandas as pd

df = pd.read_csv('data/mining_sites_clean.csv')
df.shape

(48414, 20)

In [19]:
from sqlalchemy import create_engine

# Replace 'your_password' with your actual postgres password
engine = create_engine('postgresql://postgres:pedrojose@localhost:5432/mining_explorer')

print("Connection successful" if engine.connect() else "Connection failed")

Connection successful

In [21]:
from geoalchemy2 import Geometry, WKTElement

# Rename columns to match the database table (Postgres doesn't like uppercase or special chars)
df_db = df.rename(columns={
    'site_commo': 'site_commodity',
    'site_type_': 'site_type',
    'site_sub_t': 'site_sub_type',
    'target_com': 'target_commodity',
    'confidenti': 'confidentiality',
    'point_conf': 'point_confidence',
    'extract_da': 'extract_date'
})

# Create the geometry column from latitude/longitude
df_db['location'] = df_db.apply(
    lambda row: WKTElement(f"POINT({row['longitude']} {row['latitude']})", srid=4326),
    axis=1
)

# Drop the separate lat/lon columns since they're now inside 'location'
df_db = df_db.drop(columns=['latitude', 'longitude'])

df_db.shape

(48414, 19)

In [22]:
df_db.to_sql(
    'mining_sites',
    engine,
    if_exists='append',
    index=False,
    dtype={'location': Geometry('POINT', srid=4326)}
)

print(f"Inserted {len(df_db)} rows into mining_sites")

Inserted 48414 rows into mining_sites